//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualKubelet) DeepCopyInto(out *VirtualKubelet) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualKubelet.
func (in *VirtualKubelet) DeepCopy() *VirtualKubelet {
	if in == nil {
		return nil
	}
	out := new(VirtualKubelet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualKubeletConfig) DeepCopyInto(out *VirtualKubeletConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualKubeletConfig.
func (in *VirtualKubeletConfig) DeepCopy() *VirtualKubeletConfig {
	if in == nil {
		return nil
	}
	out := new(VirtualKubeletConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualKubeletConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualKubeletConfigInitializationStatus) DeepCopyInto(out *VirtualKubeletConfigInitializationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualKubeletConfigInitializationStatus.
func (in *VirtualKubeletConfigInitializationStatus) DeepCopy() *VirtualKubeletConfigInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualKubeletConfigInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualKubeletConfigList) DeepCopyInto(out *VirtualKubeletConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualKubeletConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualKubeletConfigList.
func (in *VirtualKubeletConfigList) DeepCopy() *VirtualKubeletConfigList {
	if in == nil {
		return nil
	}
	out := new(VirtualKubeletConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualKubeletConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualKubeletConfigSpec) DeepCopyInto(out *VirtualKubeletConfigSpec) {
	*out = *in
	in.VirtualKubelet.DeepCopyInto(&out.VirtualKubelet)
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]v1beta2.User, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]v1beta2.File, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualKubeletConfigSpec.
func (in *VirtualKubeletConfigSpec) DeepCopy() *VirtualKubeletConfigSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualKubeletConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualKubeletConfigStatus) DeepCopyInto(out *VirtualKubeletConfigStatus) {
	*out = *in
	if in.DataSecretName != nil {
		in, out := &in.DataSecretName, &out.DataSecretName
		*out = new(string)
		**out = **in
	}
	out.Initialization = in.Initialization
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualKubeletConfigStatus.
func (in *VirtualKubeletConfigStatus) DeepCopy() *VirtualKubeletConfigStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualKubeletConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualKubeletConfigTemplate) DeepCopyInto(out *VirtualKubeletConfigTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualKubeletConfigTemplate.
func (in *VirtualKubeletConfigTemplate) DeepCopy() *VirtualKubeletConfigTemplate {
	if in == nil {
		return nil
	}
	out := new(VirtualKubeletConfigTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualKubeletConfigTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualKubeletConfigTemplateList) DeepCopyInto(out *VirtualKubeletConfigTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualKubeletConfigTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualKubeletConfigTemplateList.
func (in *VirtualKubeletConfigTemplateList) DeepCopy() *VirtualKubeletConfigTemplateList {
	if in == nil {
		return nil
	}
	out := new(VirtualKubeletConfigTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualKubeletConfigTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualKubeletConfigTemplateResource) DeepCopyInto(out *VirtualKubeletConfigTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualKubeletConfigTemplateResource.
func (in *VirtualKubeletConfigTemplateResource) DeepCopy() *VirtualKubeletConfigTemplateResource {
	if in == nil {
		return nil
	}
	out := new(VirtualKubeletConfigTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualKubeletConfigTemplateSpec) DeepCopyInto(out *VirtualKubeletConfigTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualKubeletConfigTemplateSpec.
func (in *VirtualKubeletConfigTemplateSpec) DeepCopy() *VirtualKubeletConfigTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualKubeletConfigTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualKubeletConfigTemplateStatus) DeepCopyInto(out *VirtualKubeletConfigTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualKubeletConfigTemplateStatus.
func (in *VirtualKubeletConfigTemplateStatus) DeepCopy() *VirtualKubeletConfigTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualKubeletConfigTemplateStatus)
	in.DeepCopyInto(out)
	return out
}
